---
Name: abc-silverstripe-social-routes
After: framework/routes#coreroutes
---
Director:
  rules:
    TwitterAuthenticator: TwitterAuthenticator
    FBAuthenticator: FBAuthenticator
    InstagramAuthenticator: InstagramAuthenticator
    abc-social-admin: SocialAdmin
